<a href="https://colab.research.google.com/github/wurifah/Bisaai/blob/main/klasifikasiteks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('Womens Clothing E-Commerce Reviews.csv')
df.head()

Unnamed: 0  Clothing ID  Age  ...   Division Name Department Name  Class Name
0           0          767   33  ...       Initmates        Intimate   Intimates
1           1         1080   34  ...         General         Dresses     Dresses
2           2         1077   60  ...         General         Dresses     Dresses
3           3         1049   50  ...  General Petite         Bottoms       Pants
4           4          847   47  ...         General            Tops     Blouses

[5 rows x 11 columns]

In [ ]:
df.shape

(23486, 11)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


In [ ]:
df.describe()

Unnamed: 0   Clothing ID  ...  Recommended IND  Positive Feedback Count
count  23486.000000  23486.000000  ...     23486.000000             23486.000000
mean   11742.500000    918.118709  ...         0.822362                 2.535936
std     6779.968547    203.298980  ...         0.382216                 5.702202
min        0.000000      0.000000  ...         0.000000                 0.000000
25%     5871.250000    861.000000  ...         1.000000                 0.000000
50%    11742.500000    936.000000  ...         1.000000                 1.000000
75%    17613.750000   1078.000000  ...         1.000000                 3.000000
max    23485.000000   1205.000000  ...         1.000000               122.000000

[8 rows x 6 columns]

In [ ]:
df.dropna(axis = 0, subset=['Review Text','Class Name'], inplace = True)
df.head()

Unnamed: 0  Clothing ID  Age  ...   Division Name Department Name  Class Name
0           0          767   33  ...       Initmates        Intimate   Intimates
1           1         1080   34  ...         General         Dresses     Dresses
2           2         1077   60  ...         General         Dresses     Dresses
3           3         1049   50  ...  General Petite         Bottoms       Pants
4           4          847   47  ...         General            Tops     Blouses

[5 rows x 11 columns]

In [ ]:
np.nan_to_num(df)

array([[0, 767, 33, ..., 'Initmates', 'Intimate', 'Intimates'],
       [1, 1080, 34, ..., 'General', 'Dresses', 'Dresses'],
       [2, 1077, 60, ..., 'General', 'Dresses', 'Dresses'],
       ...,
       [23483, 1104, 31, ..., 'General Petite', 'Dresses', 'Dresses'],
       [23484, 1084, 28, ..., 'General', 'Dresses', 'Dresses'],
       [23485, 1104, 52, ..., 'General Petite', 'Dresses', 'Dresses']],
      dtype=object)

In [ ]:
df.isna()

Unnamed: 0  Clothing ID  ...  Department Name  Class Name
0           False        False  ...            False       False
1           False        False  ...            False       False
2           False        False  ...            False       False
3           False        False  ...            False       False
4           False        False  ...            False       False
...           ...          ...  ...              ...         ...
23481       False        False  ...            False       False
23482       False        False  ...            False       False
23483       False        False  ...            False       False
23484       False        False  ...            False       False
23485       False        False  ...            False       False

[22628 rows x 11 columns]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

x_train, x_test, y_train, y_test = train_test_split(df['Review Text'].values.astype('U'), df['Class Name'], train_size = 0.75, random_state = 45)
x_train = vectorizer.fit_transform(np.nan_to_num(x_train))
x_test = vectorizer.transform(x_test)

In [ ]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(x_train, y_train)
y_pred = nb.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
confusion_matrix(y_pred, y_test)

array([[ 281,   22,   10,    2,   12,    1,  113,    3,    0,    3,    1,
           5,    2,   12,    5,   16,   10,    1],
       [  93, 1453,   59,   27,   58,    4,  115,    6,    2,   49,   39,
          81,   20,  128,    4,   44,   42,   13],
       [   0,    1,    6,    0,    2,    0,    2,    0,    0,    0,    0,
           0,    0,    1,    0,    9,    1,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,   10,    0,    1,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    1,    0,  206,    2,    0,    9,    9,    0,
          31,    5,    0,    2,    0,    1,    0],
       [ 355,   58,  150,   19,   84,    7,  887,   25,    2,   59,   15,
          20,   12,   27,   21,  141,   25,    6],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],


In [ ]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

     Blouses       0.38      0.56      0.46       499
     Dresses       0.94      0.65      0.77      2237
  Fine gauge       0.02      0.27      0.04        22
   Intimates       0.00      0.00      0.00         0
     Jackets       0.05      0.91      0.10        11
       Jeans       0.83      0.77      0.80       266
       Knits       0.78      0.46      0.58      1913
    Layering       0.00      0.00      0.00         0
     Legwear       0.00      0.00      0.00         0
      Lounge       0.04      0.50      0.07        12
   Outerwear       0.00      0.00      0.00         1
       Pants       0.62      0.61      0.62       381
      Shorts       0.00      0.00      0.00         0
      Skirts       0.16      0.92      0.28        36
       Sleep       0.00      0.00      0.00         0
    Sweaters       0.41      0.54      0.47       272
        Swim       0.07      1.00      0.14         7
       Trend       0.00    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
MAX_NB_WORDS = 50000
MAX_SEQUENCE_LENGTH = 250
EMBEDDING_DIM = 100
tokenizer = Tokenizer(num_words=MAX_NB_WORDS, filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}=', lower = True)
tokenizer.fit_on_texts(df['Review Text'].values)
word_index = tokenizer.word_index
print('Found %s unique tokens. ' %len(word_index))

x = tokenizer.texts_to_sequences(df['Review Text'].values)
x = pad_sequences(x, maxlen=MAX_SEQUENCE_LENGTH)
print('Shape of data tensor: ', x.shape)

Found 15613 unique tokens. 
Shape of data tensor:  (22628, 250)


In [ ]:
y = pd.get_dummies(df['Class Name']).values
print('Shape of label tensor: ', y.shape)

Shape of label tensor:  (22628, 20)


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state=45)
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(20365, 250) (20365, 20)
(2263, 250) (2263, 20)


In [ ]:
from keras.models import Sequential
from keras.layers import Embedding, SpatialDropout1D, LSTM
from keras.layers.core import Dense

model = Sequential()
model.add(Embedding(MAX_NB_WORDS, EMBEDDING_DIM, input_length =x.shape[1]))
model.add(SpatialDropout1D(0.2))
model.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(20, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

epochs = 5
batch_size = 64
model.fit(x_train, y_train, epochs=epochs, batch_size=batch_size, validation_split=0.1)

Epoch 1/5
287/287 [==============================] - 250s 852ms/step - loss: 2.1873 - accuracy: 0.3169 - val_loss: 1.7859 - val_accuracy: 0.4521
Epoch 2/5
287/287 [==============================] - 240s 837ms/step - loss: 1.6679 - accuracy: 0.4741 - val_loss: 1.6259 - val_accuracy: 0.4821
Epoch 3/5
287/287 [==============================] - 239s 832ms/step - loss: 1.5819 - accuracy: 0.4932 - val_loss: 1.7385 - val_accuracy: 0.4678
Epoch 4/5
287/287 [==============================] - 284s 990ms/step - loss: 1.6076 - accuracy: 0.4894 - val_loss: 1.6698 - val_accuracy: 0.4624
Epoch 5/5
287/287 [==============================] - 279s 972ms/step - loss: 1.4643 - accuracy: 0.5292 - val_loss: 1.5105 - val_accuracy: 0.4988


In [ ]:
y_pred = model.predict(x_test)
y_pred.shape

(2263, 20)

In [ ]:
from mlxtend.preprocessing import one_hot

result = np.where(y_pred[0] == np.amax(y_pred[0]))
one_hot(result[0])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1.]])

In [ ]:
import joblib
joblib.dump(model, 'model_LSTM.csv')
print('model saved')

INFO:tensorflow:Assets written to: ram://0017f84a-1c59-480b-b081-cace0d866063/assets


model saved
